### ISSUE TITLE
PortalView has an unnecessary dependency on AppCompatActivity, and fails without throwing a proper exception.

### ISSUE THREAD

**Issue by mattmckeon** [ionic-team/ionic-portals-android#47]
[PortalView](https://github.com/ionic-team/ionic-portals-android/blob/e1769d447201824e402922e5bd7a6f9d10b196fd/IonicPortals/src/main/kotlin/io/ionic/portals/PortalView.kt#L14) requires its containing activity to implement [AppCompatActivity](https://developer.android.com/reference/androidx/appcompat/app/AppCompatActivity). This is bad for applications using Jetpack Compose, because AppCompatActivity requires you to use a theme (AppCompatTheme) that is incompatible with the recommended Material theme in Compose apps. 

This is an overly restrictive approach, for two reasons:

1.  The only method PortalView [uses](https://github.com/ionic-team/ionic-portals-android/blob/e1769d447201824e402922e5bd7a6f9d10b196fd/IonicPortals/src/main/kotlin/io/ionic/portals/PortalView.kt#L129)  from AppCompatActivity, [getSupportFragmentManager](https://developer.android.com/reference/androidx/fragment/app/FragmentActivity#getSupportFragmentManager()), is actually from AppCompatActivity's base class, [FragmentActivity](https://developer.android.com/reference/androidx/fragment/app/FragmentActivity). The cast here could be to FragmentActivity, which is from androidx.fragment and has a minSDK of 14 vs Portals overall min SDK of 22. 
2. Because all that's required is the FragmentManager, PortalView could optionally take a [Lazy](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/lazy.html)-valued FragmentManager as a required constructor parameter. This would be first evaluated at load time, after the view has been attached, and remove the dependency on a particular implementation of Activity.

Finally, if after all this the PortalView is still in an invalid context, the code should check the cast and throw a proper exception with an informative error message, as opposed to a class cast exception.

**Comment by Steven0351** [comment]
Our Android dev @carlpoole is out at the moment and is the only person who can speak intelligently on the points you've brought up. Regarding the min SDK comment, Portals follows the minimum SDK requirements of [Capacitor](https://capacitorjs.com/docs/main/reference/support-policy#minimum-supported-platforms).

**Comment by carlpoole** [comment]
Thanks for the feedback. The AppCompatActivity is a constraint currently required for core dependency [Capacitor](https://github.com/ionic-team/capacitor/blob/5a6971f73a2022d49f68f1898af7f41a85310e3c/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L98) and [Cordova](https://github.com/apache/cordova-android/blob/94234d988ec2f2eb14ebf551e97ef7d9b5b11ec9/framework/src/org/apache/cordova/CordovaInterfaceImpl.java#L55) 

Our team works closely with Capacitor and we have thoughts on rearchitecting the project at large to allow for Portals to support Compose theming.

**Comment by carlpoole** [comment]
Current project depends on Capacitor constraints.
